name: Documentation Issue
description: Report an issue with the NuGet Client documentation
labels: ["Type:Docs", "Triage:Untriaged"]

body:
  - type: markdown
    attributes:
      value: |
        **Docs Page URL**
        Please provide the URL of the NuGet documentation page where you found the issue.

  - type: textarea
    id: description
    attributes:
      label: Description of the Issue
      description: A clear and concise description of what the issue is.
      placeholder: Describe the issue...

  - type: textarea
    id: suggested-fix
    attributes:
      label: Suggested Fix
      description: If you have a suggestion for how to fix the issue, please provide it here.
      placeholder: Suggest a fix...

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: Provide additional context...
